// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef SILABS_ZNET_BOOKKEEPING_H
#define SILABS_ZNET_BOOKKEEPING_H


#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include "af.h"

void emAfInit(void);

void emAfTick(void);

void emAfResetAttributes(uint8_t endpointId);

bool emAfPreCommandReceived(EmberAfClusterCommand* cmd);

bool emAfPreZDOMessageReceived(EmberNodeId emberNodeId,EmberApsFrame* apsFrame,uint8_t* message,uint16_t length);

bool emAfRetrieveAttributeAndCraftResponse(uint8_t endpoint, EmberAfClusterId clusterId, EmberAfAttributeId attrId, uint8_t mask, uint16_t maunfacturerCode, uint16_t readLength);

void emAfZigbeeKeyEstablishment(EmberEUI64 partner, EmberKeyStatus status);

bool emAfReadAttributesResponse(EmberAfClusterId clusterId,uint8_t* buffer,uint16_t bufLen);

bool emAfReportAttributes(EmberAfClusterId clusterId,uint8_t * buffer,uint16_t bufLen);

#endif // SILABS_ZNET_BOOKKEEPING_H
