// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef SILABS_EMBER_AF_COMMAND_PARSE_HEADER
#define SILABS_EMBER_AF_COMMAND_PARSE_HEADER


// This is a set of generated prototype for functions that parse the
// the incomming message, and call appropriate command handler.

#endif // SILABS_EMBER_AF_COMMAND_PARSE_HEADER
