// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// This c file provides stubs for all callbacks. These stubs
// will be used in the case where user defined implementations
// of the callbacks have not been provided.
#include "app/framework/include/af.h"
// Stubs required for implemented stack handlers.


#ifdef EZSP_HOST
#else // ! EZSP_HOST
#endif // EZSP_HOST
